'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.1378
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On


Namespace ServiceReference
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServiceReference.IRead")>  _
    Public Interface IRead
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRead/VwZoneList", ReplyAction:="http://tempuri.org/IRead/VwZoneListResponse")>  _
        Function VwZoneList() As String()
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IRead/VwZoneDetail", ReplyAction:="http://tempuri.org/IRead/VwZoneDetailResponse")>  _
        Function VwZoneDetail(ByVal intVwZoneId As Integer) As String()
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Public Interface IReadChannel
        Inherits ServiceReference.IRead, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")>  _
    Partial Public Class ReadClient
        Inherits System.ServiceModel.ClientBase(Of ServiceReference.IRead)
        Implements ServiceReference.IRead
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function VwZoneList() As String() Implements ServiceReference.IRead.VwZoneList
            Return MyBase.Channel.VwZoneList
        End Function
        
        Public Function VwZoneDetail(ByVal intVwZoneId As Integer) As String() Implements ServiceReference.IRead.VwZoneDetail
            Return MyBase.Channel.VwZoneDetail(intVwZoneId)
        End Function
    End Class
End Namespace
